### ISSUE TITLE
TypeError: r.error.detail.map is not a function

### ISSUE THREAD

**Issue by MediGenie** [Unstructured-IO/unstructured-api-gui#14]
Any ideas why I am getting this error when i ran with an API key?

TypeError: r.error.detail.map is not a function
    at yo (http://localhost:3000/build/routes/_index-YKB4YPKL.js:7:1665)
    at mu (http://localhost:3000/build/entry.client-63UUGW27.js:6:19466)
    at Xa (http://localhost:3000/build/entry.client-63UUGW27.js:8:43659)
    at $a (http://localhost:3000/build/entry.client-63UUGW27.js:8:39459)
    at Gf (http://localhost:3000/build/entry.client-63UUGW27.js:8:39390)
    at br (http://localhost:3000/build/entry.client-63UUGW27.js:8:39250)
    at Ui (http://localhost:3000/build/entry.client-63UUGW27.js:8:35673)
    at Ha (http://localhost:3000/build/entry.client-63UUGW27.js:8:34629)
    at Cl (http://localhost:3000/build/entry.client-63UUGW27.js:1:1695)
    at MessagePort.gl (http://localhost:3000/build/entry.client-63UUGW27.js:1:2085)

**Comment by MediGenie** [comment]
my terminal output:```
 POST /?index=&_data=routes%2F_index 200 - - 2062.396 ms
GET /?index=&_data=routes%2F_index 200 - - 1.727 ms
```

**Comment by choaf** [comment]
Could it be that it's no longer sufficient to only provide the api_key_auth, but we also need the individual server_url?

s = UnstructuredClient(api_key_auth="<yourAPI>", server_url="<your url>.api.unstructuredapp.io/general/v0/general")
